# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Users/DELL/Desktop/craps/qz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"QToolBox::tab,\n"
"QPushButton,\n"
"QLabel,\n"
"QplaintextEdit, /* Kept for general styling, though plainTextEdit is removed */\n"
"QRadioButton,\n"
"QStatusBar { /* Added missing closing brace for QStatusBar */\n"
"    font-family: system-ui;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#tittle_frame {\n"
"    background-color: #393e4d;\n"
"}\n"
"\n"
"#tittle_frame QLabel {\n"
"    font-family: Zurich XBIK BT;\n"
"    font-size: 30px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QToolBoxButton {\n"
"    min-height: 35px;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                stop:0 #a6a29a, stop:0.4 #DDDDDD,\n"
"                stop:0.6 #D8D8D8, stop:1.0 #a6a29a);\n"
"    padding: 0.10px;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    font: italic;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QLabel {\n"
"    border-radius: 3px; /* Corrected typo: border-radiu to border-radius */\n"
"    padding: 5px;\n"
"    color: #0a3622;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QComboBox, QSpinBox, QLineEdit { /* Corrected: QcomboBox to QComboBox, QspinBox to QSpinBox */\n"
"    min-height: 20px;\n"
"    padding: 5px;\n"
"    font-family: Times New Roman;\n"
"    font-size: 14px;\n"
"    color: #3232CD;\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 10px;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 15px;\n"
"    border-bottom-right-radius: 5px;\n"
"    max-width: 200px;\n"
"    background-color: #2d6df4;\n"
"    font-weight: bold;\n"
"    color: #fff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(20, 100, 581, 531))
        self.toolBox.setObjectName("toolBox")
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setGeometry(QtCore.QRect(0, 0, 581, 471))
        self.page_settings.setObjectName("page_settings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_settings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.db_frame = QtWidgets.QFrame(self.page_settings)
        self.db_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.db_frame.setObjectName("db_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.db_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.db_frame)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.spinBox_num_questions = QtWidgets.QSpinBox(self.db_frame)
        self.spinBox_num_questions.setMinimum(1)
        self.spinBox_num_questions.setMaximum(20)
        self.spinBox_num_questions.setProperty("value", 20)
        self.spinBox_num_questions.setObjectName("spinBox_num_questions")
        self.horizontalLayout_2.addWidget(self.spinBox_num_questions)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 289, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.db_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.db_frame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.comboBox_category = QtWidgets.QComboBox(self.db_frame)
        self.comboBox_category.setObjectName("comboBox_category")
        self.horizontalLayout_4.addWidget(self.comboBox_category)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.db_frame, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_settings, "")
        self.page_question = QtWidgets.QWidget()
        self.page_question.setGeometry(QtCore.QRect(0, 0, 581, 471))
        self.page_question.setObjectName("page_question")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_question)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.question_frame = QtWidgets.QFrame(self.page_question)
        self.question_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.question_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.question_frame.setObjectName("question_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.question_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.info_frame = QtWidgets.QFrame(self.question_frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.question_count_label = QtWidgets.QLabel(self.info_frame)
        self.question_count_label.setGeometry(QtCore.QRect(725, 12, 38, 20))
        self.question_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.question_count_label.setObjectName("question_count_label")
        self.verticalLayout_3.addWidget(self.info_frame)
        self.questions_frame = QtWidgets.QFrame(self.question_frame)
        self.questions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.questions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questions_frame.setObjectName("questions_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.questions_frame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_question = QtWidgets.QLabel(self.questions_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_question.setFont(font)
        self.label_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question.setWordWrap(True)
        self.label_question.setObjectName("label_question")
        self.verticalLayout_2.addWidget(self.label_question)
        self.answer_frame = QtWidgets.QFrame(self.questions_frame)
        self.answer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answer_frame.setObjectName("answer_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.answer_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_opt_a = QtWidgets.QRadioButton(self.answer_frame)
        self.radioButton_opt_a.setObjectName("radioButton_opt_a")
        self.verticalLayout.addWidget(self.radioButton_opt_a)
        self.radioButton_opt_b = QtWidgets.QRadioButton(self.answer_frame)
        self.radioButton_opt_b.setObjectName("radioButton_opt_b")
        self.verticalLayout.addWidget(self.radioButton_opt_b)
        self.radioButton_opt_c = QtWidgets.QRadioButton(self.answer_frame)
        self.radioButton_opt_c.setObjectName("radioButton_opt_c")
        self.verticalLayout.addWidget(self.radioButton_opt_c)
        self.radioButton_opt_d = QtWidgets.QRadioButton(self.answer_frame)
        self.radioButton_opt_d.setObjectName("radioButton_opt_d")
        self.verticalLayout.addWidget(self.radioButton_opt_d)
        self.verticalLayout_2.addWidget(self.answer_frame)
        self.verticalLayout_3.addWidget(self.questions_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_feedback = QtWidgets.QLabel(self.question_frame)
        self.label_feedback.setText("")
        self.label_feedback.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_feedback.setFont(font)
        self.label_feedback.setObjectName("label_feedback")
        self.verticalLayout_3.addWidget(self.label_feedback)
        self.function_frame = QtWidgets.QFrame(self.question_frame)
        self.function_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.function_frame.setObjectName("function_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.function_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.function_frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_submit_answer = QtWidgets.QPushButton(self.function_frame)
        self.pushButton_submit_answer.setObjectName("pushButton_submit_answer")
        self.horizontalLayout_3.addWidget(self.pushButton_submit_answer)
        self.pushButton_next_question = QtWidgets.QPushButton(self.function_frame)
        self.pushButton_next_question.setObjectName("pushButton_next_question")
        self.horizontalLayout_3.addWidget(self.pushButton_next_question)
        self.verticalLayout_3.addWidget(self.function_frame)
        self.gridLayout_5.addWidget(self.question_frame, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_question, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 591, 70))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(100, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Documents/pz.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz"))
        self.label_14.setText(_translate("MainWindow", "Number of Questions"))
        self.pushButton_4.setText(_translate("MainWindow", "Get New Question"))
        self.label_11.setText(_translate("MainWindow", "Select Category"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_settings), _translate("MainWindow", "Settings"))
        self.question_count_label.setText(_translate("MainWindow", "1/1"))
        self.label_question.setText(_translate("MainWindow", "Question Text Will Appear Here"))
        self.radioButton_opt_a.setText(_translate("MainWindow", "Option A"))
        self.radioButton_opt_b.setText(_translate("MainWindow", "Option B"))
        self.radioButton_opt_c.setText(_translate("MainWindow", "Option C"))
        self.radioButton_opt_d.setText(_translate("MainWindow", "Option D"))
        self.pushButton.setText(_translate("MainWindow", "Try Again"))
        self.pushButton_submit_answer.setText(_translate("MainWindow", "Submit Answer"))
        self.pushButton_next_question.setText(_translate("MainWindow", "Next"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_question), _translate("MainWindow", "Question"))
        self.label_3.setText(_translate("MainWindow", "Quizz!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
